import type { CuratedConcept } from "./contribution-slot-generator";

/**
 * Curated concepts catalog for segments 04 through 10 across all 10 worlds.
 * Mapped to verified existing SVG assets on disk and aligned with each segment's theme.
 */
export const EXPANDED_CURATED_CONCEPTS: CuratedConcept[] = [
  // ==========================================
  // 1. Growing Forest (forest-04 to forest-10)
  // ==========================================
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: River Woodland Flower (Bank Flora)",
    objectName: "River Woodland Flower",
    assetFile: "woodland-flower.svg",
    defaultSegmentId: "forest-04",
    segmentName: "River Crossing",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: River Boulder (Water Terrain)",
    objectName: "River Boulder",
    assetFile: "mossy-rock.svg",
    defaultSegmentId: "forest-04",
    segmentName: "River Crossing",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Ridge Pine (Highland Tree)",
    objectName: "Ridge Pine",
    assetFile: "pine-tree.svg",
    defaultSegmentId: "forest-05",
    segmentName: "Misty Ridge",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Mountain Bird (Ridge Avian)",
    objectName: "Mountain Bird",
    assetFile: "song-bird.svg",
    defaultSegmentId: "forest-05",
    segmentName: "Misty Ridge",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Fern Deer (Sheltered Wildlife)",
    objectName: "Fern Deer",
    assetFile: "forest-deer.svg",
    defaultSegmentId: "forest-06",
    segmentName: "Whispering Ferns",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Fern Butterfly (Canopy Insect)",
    objectName: "Fern Butterfly",
    assetFile: "student-butterfly.svg",
    defaultSegmentId: "forest-06",
    segmentName: "Whispering Ferns",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Hollow Red Mushroom (Shadow Fungi)",
    objectName: "Hollow Red Mushroom",
    assetFile: "red-mushroom.svg",
    defaultSegmentId: "forest-07",
    segmentName: "Sunken Hollow",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Hollow Moss Stone (Root Bed)",
    objectName: "Hollow Moss Stone",
    assetFile: "mossy-rock.svg",
    defaultSegmentId: "forest-07",
    segmentName: "Sunken Hollow",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Crest Evergreen (Ridge Silhouette)",
    objectName: "Crest Evergreen",
    assetFile: "pine-tree.svg",
    defaultSegmentId: "forest-08",
    segmentName: "Pine Crest",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Crest Song Bird (High Lookout)",
    objectName: "Crest Song Bird",
    assetFile: "song-bird.svg",
    defaultSegmentId: "forest-08",
    segmentName: "Pine Crest",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Glade Blossom (Meadow Flora)",
    objectName: "Glade Blossom",
    assetFile: "woodland-flower.svg",
    defaultSegmentId: "forest-09",
    segmentName: "Wildflower Clearing",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Glade Butterfly (Meadow Pollinator)",
    objectName: "Glade Butterfly",
    assetFile: "student-butterfly.svg",
    defaultSegmentId: "forest-09",
    segmentName: "Wildflower Clearing",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Twilight Deer (Evening Grazer)",
    objectName: "Twilight Deer",
    assetFile: "forest-deer.svg",
    defaultSegmentId: "forest-10",
    segmentName: "Twilight Lookout",
  },
  {
    worldId: "growing-forest",
    worldName: "Growing Forest",
    categoryLabel: "🌲 Forest: Twilight Lookout Pine (Sentinel Tree)",
    objectName: "Twilight Lookout Pine",
    assetFile: "pine-tree.svg",
    defaultSegmentId: "forest-10",
    segmentName: "Twilight Lookout",
  },

  // ============================================
  // 2. Growing Universe (universe-04 to universe-10)
  // ============================================
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Nebula Probe (Deep Space Satellite)",
    objectName: "Nebula Probe",
    assetFile: "paper-satellite.svg",
    defaultSegmentId: "universe-04",
    segmentName: "Radiant Nebula",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Nebula Galaxy (Glowing Spiral)",
    objectName: "Nebula Galaxy",
    assetFile: "spiral-galaxy.svg",
    defaultSegmentId: "universe-04",
    segmentName: "Radiant Nebula",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Vista Planet (Distant Sphere)",
    objectName: "Vista Planet",
    assetFile: "paper-planet.svg",
    defaultSegmentId: "universe-05",
    segmentName: "Deep Galaxy Vista",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Vista Comet (Trailing Celestial)",
    objectName: "Vista Comet",
    assetFile: "paper-comet.svg",
    defaultSegmentId: "universe-05",
    segmentName: "Deep Galaxy Vista",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Solar Rim Moon (Orbiting Crescent)",
    objectName: "Solar Rim Moon",
    assetFile: "crescent-moon.svg",
    defaultSegmentId: "universe-06",
    segmentName: "Binary Solar Rim",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Solar Rim Asteroid (Belt Fragment)",
    objectName: "Solar Rim Asteroid",
    assetFile: "paper-asteroid.svg",
    defaultSegmentId: "universe-06",
    segmentName: "Binary Solar Rim",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Stardust Galaxy (Luminous Cluster)",
    objectName: "Stardust Galaxy",
    assetFile: "spiral-galaxy.svg",
    defaultSegmentId: "universe-07",
    segmentName: "Stardust Expanse",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Stardust Satellite (Telemetry Relay)",
    objectName: "Stardust Satellite",
    assetFile: "paper-satellite.svg",
    defaultSegmentId: "universe-07",
    segmentName: "Stardust Expanse",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Quasar Comet (High Energy Wanderer)",
    objectName: "Quasar Comet",
    assetFile: "paper-comet.svg",
    defaultSegmentId: "universe-08",
    segmentName: "Quasar Horizon",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Quasar Planet (Irradiated Orb)",
    objectName: "Quasar Planet",
    assetFile: "paper-planet.svg",
    defaultSegmentId: "universe-08",
    segmentName: "Quasar Horizon",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Pulsar Asteroid (Dense Rock)",
    objectName: "Pulsar Asteroid",
    assetFile: "paper-asteroid.svg",
    defaultSegmentId: "universe-09",
    segmentName: "Pulsar Drift",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Pulsar Crescent (Shadow Moon)",
    objectName: "Pulsar Crescent",
    assetFile: "crescent-moon.svg",
    defaultSegmentId: "universe-09",
    segmentName: "Pulsar Drift",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Void Edge Probe (Deep Beacon)",
    objectName: "Void Edge Probe",
    assetFile: "paper-satellite.svg",
    defaultSegmentId: "universe-10",
    segmentName: "Cosmic Void Edge",
  },
  {
    worldId: "growing-universe",
    worldName: "Growing Universe",
    categoryLabel: "🌌 Universe: Void Edge Comet (Last Wanderer)",
    objectName: "Void Edge Comet",
    assetFile: "paper-comet.svg",
    defaultSegmentId: "universe-10",
    segmentName: "Cosmic Void Edge",
  },

  // =========================================
  // 3. Growing Ocean (ocean-04 to ocean-10)
  // =========================================
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Current Sea Turtle (Pelagic Traveler)",
    objectName: "Current Sea Turtle",
    assetFile: "sea-turtle.svg",
    defaultSegmentId: "ocean-04",
    segmentName: "Open Blue Current",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Current Jellyfish (Drifting Medusa)",
    objectName: "Current Jellyfish",
    assetFile: "student-paper-jellyfish.svg",
    defaultSegmentId: "ocean-04",
    segmentName: "Open Blue Current",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Abyssal Submarine (Deep Trench Explorer)",
    objectName: "Abyssal Submarine",
    assetFile: "research-submarine.svg",
    defaultSegmentId: "ocean-05",
    segmentName: "Abyssal Glow Trench",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Abyssal Seashell (Luminescent Shell)",
    objectName: "Abyssal Seashell",
    assetFile: "seashell.svg",
    defaultSegmentId: "ocean-05",
    segmentName: "Abyssal Glow Trench",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Shipwreck Coral (Reef Colony)",
    objectName: "Shipwreck Coral",
    assetFile: "paper-coral.svg",
    defaultSegmentId: "ocean-06",
    segmentName: "Sunken Shipwreck Reef",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Shipwreck Clownfish (Hull Inhabitant)",
    objectName: "Shipwreck Clownfish",
    assetFile: "clownfish.svg",
    defaultSegmentId: "ocean-06",
    segmentName: "Sunken Shipwreck Reef",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Vent Submersible (Thermal Surveyor)",
    objectName: "Vent Submersible",
    assetFile: "research-submarine.svg",
    defaultSegmentId: "ocean-07",
    segmentName: "Thermal Vent Basin",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Vent Kelp (Hardy Thermal Flora)",
    objectName: "Vent Kelp",
    assetFile: "kelp-stalk.svg",
    defaultSegmentId: "ocean-07",
    segmentName: "Thermal Vent Basin",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Canopy Kelp Stalk (Towering Frond)",
    objectName: "Canopy Kelp Stalk",
    assetFile: "kelp-stalk.svg",
    defaultSegmentId: "ocean-08",
    segmentName: "Kelp Canopy Run",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Canopy Sea Turtle (Kelp Grazer)",
    objectName: "Canopy Sea Turtle",
    assetFile: "sea-turtle.svg",
    defaultSegmentId: "ocean-08",
    segmentName: "Kelp Canopy Run",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Cavern Coral (Bioluminescent Formation)",
    objectName: "Cavern Coral",
    assetFile: "paper-coral.svg",
    defaultSegmentId: "ocean-09",
    segmentName: "Bioluminescent Cavern",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Cavern Jellyfish (Glowing Medusa)",
    objectName: "Cavern Jellyfish",
    assetFile: "student-paper-jellyfish.svg",
    defaultSegmentId: "ocean-09",
    segmentName: "Bioluminescent Cavern",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Trench Floor Seashell (Ancient Bivalve)",
    objectName: "Trench Floor Seashell",
    assetFile: "seashell.svg",
    defaultSegmentId: "ocean-10",
    segmentName: "Deep Trench Floor",
  },
  {
    worldId: "growing-ocean",
    worldName: "Growing Ocean",
    categoryLabel: "🌊 Ocean: Deep Trench Submarine (Ultimate Descent)",
    objectName: "Deep Trench Submarine",
    assetFile: "research-submarine.svg",
    defaultSegmentId: "ocean-10",
    segmentName: "Deep Trench Floor",
  },

  // ========================================
  // 4. Growing City (city-04 to city-10)
  // ========================================
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Park Street Tree (Urban Foliage)",
    objectName: "Park Street Tree",
    assetFile: "street-tree.svg",
    defaultSegmentId: "city-04",
    segmentName: "Central Green Park",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Green Park Bench (Rest Spot)",
    objectName: "Green Park Bench",
    assetFile: "park-bench.svg",
    defaultSegmentId: "city-04",
    segmentName: "Central Green Park",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Skyline Street Lamp (Avenue Light)",
    objectName: "Skyline Street Lamp",
    assetFile: "street-lamp.svg",
    defaultSegmentId: "city-05",
    segmentName: "Towering Skyline",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Skyline Mailbox (Downtown Postal)",
    objectName: "Skyline Mailbox",
    assetFile: "city-mailbox.svg",
    defaultSegmentId: "city-05",
    segmentName: "Towering Skyline",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Promenade Bicycle (Harbor Commuter)",
    objectName: "Promenade Bicycle",
    assetFile: "paper-bicycle.svg",
    defaultSegmentId: "city-06",
    segmentName: "Harbor Promenade",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Promenade Street Lamp (Pier Lantern)",
    objectName: "Promenade Street Lamp",
    assetFile: "street-lamp.svg",
    defaultSegmentId: "city-06",
    segmentName: "Harbor Promenade",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Warehouse Tram (Depot Transit)",
    objectName: "Warehouse Tram",
    assetFile: "paper-tram.svg",
    defaultSegmentId: "city-07",
    segmentName: "Old Brick Warehouse",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Warehouse Bench (Alley Rest)",
    objectName: "Warehouse Bench",
    assetFile: "park-bench.svg",
    defaultSegmentId: "city-07",
    segmentName: "Old Brick Warehouse",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Artisan Alley Bicycle (Courier Cycle)",
    objectName: "Artisan Alley Bicycle",
    assetFile: "paper-bicycle.svg",
    defaultSegmentId: "city-08",
    segmentName: "Artisan Alley",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Artisan Mailbox (Letter Drop)",
    objectName: "Artisan Mailbox",
    assetFile: "city-mailbox.svg",
    defaultSegmentId: "city-08",
    segmentName: "Artisan Alley",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Plaza Street Tree (Ornamental Tree)",
    objectName: "Plaza Street Tree",
    assetFile: "street-tree.svg",
    defaultSegmentId: "city-09",
    segmentName: "Civic Plaza",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Plaza Street Lamp (Civic Illumination)",
    objectName: "Plaza Street Lamp",
    assetFile: "street-lamp.svg",
    defaultSegmentId: "city-09",
    segmentName: "Civic Plaza",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Metro Junction Tram (Hub Rail)",
    objectName: "Metro Junction Tram",
    assetFile: "paper-tram.svg",
    defaultSegmentId: "city-10",
    segmentName: "Metro Junction",
  },
  {
    worldId: "growing-city",
    worldName: "Growing City",
    categoryLabel: "🏙️ City: Metro Postal Box (Terminal Mailbox)",
    objectName: "Metro Postal Box",
    assetFile: "city-mailbox.svg",
    defaultSegmentId: "city-10",
    segmentName: "Metro Junction",
  },

  // ============================================
  // 5. Growing Village (village-04 to village-10)
  // ============================================
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Workshop Cart (Artisan Wagon)",
    objectName: "Workshop Cart",
    assetFile: "wooden-cart.svg",
    defaultSegmentId: "village-04",
    segmentName: "Artisan Workshop Quarter",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Workshop Lantern (Evening Craft Light)",
    objectName: "Workshop Lantern",
    assetFile: "village-lantern.svg",
    defaultSegmentId: "village-04",
    segmentName: "Artisan Workshop Quarter",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Village Green Fence (Common Enclosure)",
    objectName: "Village Green Fence",
    assetFile: "village-fence.svg",
    defaultSegmentId: "village-05",
    segmentName: "Festive Village Green",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Village Green Flower Pot (Festival Planter)",
    objectName: "Village Green Flower Pot",
    assetFile: "flower-pot.svg",
    defaultSegmentId: "village-05",
    segmentName: "Festive Village Green",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Mill Pond Stone Well (Waterside Well)",
    objectName: "Mill Pond Stone Well",
    assetFile: "stone-well.svg",
    defaultSegmentId: "village-06",
    segmentName: "Old Mill Pond",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Mill Pond Basket (Reed Basket)",
    objectName: "Mill Pond Basket",
    assetFile: "market-basket.svg",
    defaultSegmentId: "village-06",
    segmentName: "Old Mill Pond",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Orchard Harvest Basket (Fruit Hamper)",
    objectName: "Orchard Harvest Basket",
    assetFile: "market-basket.svg",
    defaultSegmentId: "village-07",
    segmentName: "Orchard Lane",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Orchard Fence (Woodland Boundary)",
    objectName: "Orchard Fence",
    assetFile: "village-fence.svg",
    defaultSegmentId: "village-07",
    segmentName: "Orchard Lane",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Timber Bridge Lantern (Crossing Light)",
    objectName: "Timber Bridge Lantern",
    assetFile: "village-lantern.svg",
    defaultSegmentId: "village-08",
    segmentName: "Timber Bridge",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Timber Bridge Cart (Bridge Hauler)",
    objectName: "Timber Bridge Cart",
    assetFile: "wooden-cart.svg",
    defaultSegmentId: "village-08",
    segmentName: "Timber Bridge",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Bakers Bread Basket (Fresh Loaves)",
    objectName: "Bakers Bread Basket",
    assetFile: "market-basket.svg",
    defaultSegmentId: "village-09",
    segmentName: "Bakers Row",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Bakers Row Flower Pot (Window Box)",
    objectName: "Bakers Row Flower Pot",
    assetFile: "flower-pot.svg",
    defaultSegmentId: "village-09",
    segmentName: "Bakers Row",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Hillside Chapel Lantern (Sanctuary Beacon)",
    objectName: "Hillside Chapel Lantern",
    assetFile: "village-lantern.svg",
    defaultSegmentId: "village-10",
    segmentName: "Hillside Chapel",
  },
  {
    worldId: "growing-village",
    worldName: "Growing Village",
    categoryLabel: "🏡 Village: Chapel Flower Pot (Courtyard Floral)",
    objectName: "Chapel Flower Pot",
    assetFile: "flower-pot.svg",
    defaultSegmentId: "village-10",
    segmentName: "Hillside Chapel",
  },

  // ===========================================
  // 6. Growing Island (island-04 to island-10)
  // ===========================================
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Bluff Parrot (Cliff Seabird)",
    objectName: "Bluff Parrot",
    assetFile: "tropical-parrot.svg",
    defaultSegmentId: "island-04",
    segmentName: "Coastal Lookout Bluff",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Bluff Seashell (Tide Artifact)",
    objectName: "Bluff Seashell",
    assetFile: "island-seashell.svg",
    defaultSegmentId: "island-04",
    segmentName: "Coastal Lookout Bluff",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Beacon Point Palm (Signal Tree)",
    objectName: "Beacon Point Palm",
    assetFile: "coconut-palm.svg",
    defaultSegmentId: "island-05",
    segmentName: "Historic Beacon Point",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Beacon Point Flower (Coastal Blossom)",
    objectName: "Beacon Point Flower",
    assetFile: "tropical-flower.svg",
    defaultSegmentId: "island-05",
    segmentName: "Historic Beacon Point",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Hidden Cove Canoe (Secret Mooring)",
    objectName: "Hidden Cove Canoe",
    assetFile: "wooden-canoe.svg",
    defaultSegmentId: "island-06",
    segmentName: "Hidden Sea Cove",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Hidden Cove Seashell (Pristine Shell)",
    objectName: "Hidden Cove Seashell",
    assetFile: "island-seashell.svg",
    defaultSegmentId: "island-06",
    segmentName: "Hidden Sea Cove",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Coral Atoll Parrot (Reef Flyer)",
    objectName: "Coral Atoll Parrot",
    assetFile: "tropical-parrot.svg",
    defaultSegmentId: "island-07",
    segmentName: "Coral Atoll",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Coral Atoll Palm (Lagoon Tree)",
    objectName: "Coral Atoll Palm",
    assetFile: "coconut-palm.svg",
    defaultSegmentId: "island-07",
    segmentName: "Coral Atoll",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Waterfall Tropical Flower (Misty Orchid)",
    objectName: "Waterfall Tropical Flower",
    assetFile: "tropical-flower.svg",
    defaultSegmentId: "island-08",
    segmentName: "Jungle Waterfall",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Waterfall Parrot (Jungle Canopy)",
    objectName: "Waterfall Parrot",
    assetFile: "tropical-parrot.svg",
    defaultSegmentId: "island-08",
    segmentName: "Jungle Waterfall",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Tide Pool Seashell (Shoreline Treasure)",
    objectName: "Tide Pool Seashell",
    assetFile: "island-seashell.svg",
    defaultSegmentId: "island-09",
    segmentName: "Tide Pool Terraces",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Tide Pool Flower (Coastal Flora)",
    objectName: "Tide Pool Flower",
    assetFile: "tropical-flower.svg",
    defaultSegmentId: "island-09",
    segmentName: "Tide Pool Terraces",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Sandbar Wooden Canoe (Beach Landing)",
    objectName: "Sandbar Wooden Canoe",
    assetFile: "wooden-canoe.svg",
    defaultSegmentId: "island-10",
    segmentName: "Starfish Sandbar",
  },
  {
    worldId: "growing-island",
    worldName: "Growing Island",
    categoryLabel: "🏝️ Island: Sandbar Lighthouse View (Horizon Beacon)",
    objectName: "Sandbar Lighthouse View",
    assetFile: "island-lighthouse.svg",
    defaultSegmentId: "island-10",
    segmentName: "Starfish Sandbar",
  },

  // ========================================
  // 7. Growing Farm (farm-04 to farm-10)
  // ========================================
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Orchard Watering Can (Tree Care)",
    objectName: "Orchard Watering Can",
    assetFile: "watering-can.svg",
    defaultSegmentId: "farm-04",
    segmentName: "Apple Orchard Valley",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Orchard Sheep (Undergrowth Grazer)",
    objectName: "Orchard Sheep",
    assetFile: "pasture-sheep.svg",
    defaultSegmentId: "farm-04",
    segmentName: "Apple Orchard Valley",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Harvest Plateau Scarecrow (Field Guardian)",
    objectName: "Harvest Plateau Scarecrow",
    assetFile: "scarecrow.svg",
    defaultSegmentId: "farm-05",
    segmentName: "Harvest Barn Plateau",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Harvest Plateau Pumpkin (Autumn Prize)",
    objectName: "Harvest Plateau Pumpkin",
    assetFile: "harvest-pumpkin.svg",
    defaultSegmentId: "farm-05",
    segmentName: "Harvest Barn Plateau",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Sunflower Field Sheep (Sunny Pasture)",
    objectName: "Sunflower Field Sheep",
    assetFile: "pasture-sheep.svg",
    defaultSegmentId: "farm-06",
    segmentName: "Sunflower Meadows",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Sunflower Wheat Sheaf (Golden Grain)",
    objectName: "Sunflower Wheat Sheaf",
    assetFile: "wheat-bundle.svg",
    defaultSegmentId: "farm-06",
    segmentName: "Sunflower Meadows",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Duck Pond Watering Can (Pondside Tool)",
    objectName: "Duck Pond Watering Can",
    assetFile: "watering-can.svg",
    defaultSegmentId: "farm-07",
    segmentName: "Quiet Duck Pond",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Duck Pond Windmill (Aeration Mill)",
    objectName: "Duck Pond Windmill",
    assetFile: "pasture-windmill.svg",
    defaultSegmentId: "farm-07",
    segmentName: "Quiet Duck Pond",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Stone Silo Wheat Bundle (Stored Harvest)",
    objectName: "Stone Silo Wheat Bundle",
    assetFile: "wheat-bundle.svg",
    defaultSegmentId: "farm-08",
    segmentName: "Old Stone Silo",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Stone Silo Scarecrow (Perimeter Watcher)",
    objectName: "Stone Silo Scarecrow",
    assetFile: "scarecrow.svg",
    defaultSegmentId: "farm-08",
    segmentName: "Old Stone Silo",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Haystack Pasture Sheep (Woolly Companion)",
    objectName: "Haystack Pasture Sheep",
    assetFile: "pasture-sheep.svg",
    defaultSegmentId: "farm-09",
    segmentName: "Haystack Terrace",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Haystack Pumpkin (Stashed Gourd)",
    objectName: "Haystack Pumpkin",
    assetFile: "harvest-pumpkin.svg",
    defaultSegmentId: "farm-09",
    segmentName: "Haystack Terrace",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Vineyard Windmill (Valley Breeze)",
    objectName: "Vineyard Windmill",
    assetFile: "pasture-windmill.svg",
    defaultSegmentId: "farm-10",
    segmentName: "Rustic Vineyard",
  },
  {
    worldId: "growing-farm",
    worldName: "Growing Farm",
    categoryLabel: "🚜 Farm: Vineyard Watering Can (Vine Sprinkler)",
    objectName: "Vineyard Watering Can",
    assetFile: "watering-can.svg",
    defaultSegmentId: "farm-10",
    segmentName: "Rustic Vineyard",
  },

  // ============================================
  // 8. Growing Campus (campus-04 to campus-10)
  // ============================================
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Garden Campus Bench (Student Seating)",
    objectName: "Garden Campus Bench",
    assetFile: "campus-bench.svg",
    defaultSegmentId: "campus-04",
    segmentName: "Student Union Garden",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Garden Planter (Decorative Shrubs)",
    objectName: "Garden Planter",
    assetFile: "campus-planter.svg",
    defaultSegmentId: "campus-04",
    segmentName: "Student Union Garden",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Hilltop Telescope (Stargazer Scope)",
    objectName: "Hilltop Telescope",
    assetFile: "campus-telescope.svg",
    defaultSegmentId: "campus-05",
    segmentName: "Hilltop Observatory",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Astronomy Books (Stellar Atlas)",
    objectName: "Astronomy Books",
    assetFile: "stack-of-books.svg",
    defaultSegmentId: "campus-05",
    segmentName: "Hilltop Observatory",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Greenhouse Planter (Exotic Flora)",
    objectName: "Greenhouse Planter",
    assetFile: "campus-planter.svg",
    defaultSegmentId: "campus-06",
    segmentName: "Botanical Greenhouse",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Greenhouse Student Backpack (Botany Field Kit)",
    objectName: "Greenhouse Student Backpack",
    assetFile: "student-backpack.svg",
    defaultSegmentId: "campus-06",
    segmentName: "Botanical Greenhouse",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Clocktower Campus Bicycle (Commuter Rack)",
    objectName: "Clocktower Campus Bicycle",
    assetFile: "student-bicycle.svg",
    defaultSegmentId: "campus-07",
    segmentName: "Clocktower Quad",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Clocktower Bench (Courtyard Seat)",
    objectName: "Clocktower Bench",
    assetFile: "campus-bench.svg",
    defaultSegmentId: "campus-07",
    segmentName: "Clocktower Quad",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Archway Student Bicycle (Campus Ride)",
    objectName: "Archway Student Bicycle",
    assetFile: "student-bicycle.svg",
    defaultSegmentId: "campus-08",
    segmentName: "Founders Archway",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Archway Book Stack (Study Session)",
    objectName: "Archway Book Stack",
    assetFile: "stack-of-books.svg",
    defaultSegmentId: "campus-08",
    segmentName: "Founders Archway",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Amphitheater Student Backpack (Auditorium Bag)",
    objectName: "Amphitheater Student Backpack",
    assetFile: "student-backpack.svg",
    defaultSegmentId: "campus-09",
    segmentName: "Campus Amphitheater",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Amphitheater Planter (Stage Shrub)",
    objectName: "Amphitheater Planter",
    assetFile: "campus-planter.svg",
    defaultSegmentId: "campus-09",
    segmentName: "Campus Amphitheater",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Riverside Student Bicycle (Waterfront Path)",
    objectName: "Riverside Student Bicycle",
    assetFile: "student-bicycle.svg",
    defaultSegmentId: "campus-10",
    segmentName: "Riverside Path",
  },
  {
    worldId: "growing-campus",
    worldName: "Growing Campus",
    categoryLabel: "🏛️ Campus: Riverside Campus Bench (Scenic Outlook)",
    objectName: "Riverside Campus Bench",
    assetFile: "campus-bench.svg",
    defaultSegmentId: "campus-10",
    segmentName: "Riverside Path",
  },

  // ===========================================
  // 9. Fantasy World (fantasy-04 to fantasy-10)
  // ===========================================
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Isle Floating Crystal (Levitating Gem)",
    objectName: "Isle Floating Crystal",
    assetFile: "floating-crystal.svg",
    defaultSegmentId: "fantasy-04",
    segmentName: "Floating Crystal Isle",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Isle Magic Mushroom (Fey Shroom)",
    objectName: "Isle Magic Mushroom",
    assetFile: "magic-mushroom.svg",
    defaultSegmentId: "fantasy-04",
    segmentName: "Floating Crystal Isle",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Dragon Peak Egg (Wyrm Clutch)",
    objectName: "Dragon Peak Egg",
    assetFile: "dragon-egg.svg",
    defaultSegmentId: "fantasy-05",
    segmentName: "Starlit Dragon Peak",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Dragon Peak Spellbook (Draconic Tome)",
    objectName: "Dragon Peak Spellbook",
    assetFile: "ancient-spellbook.svg",
    defaultSegmentId: "fantasy-05",
    segmentName: "Starlit Dragon Peak",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Elven Bridge Rune Stone (Ward Marker)",
    objectName: "Elven Bridge Rune Stone",
    assetFile: "rune-stone.svg",
    defaultSegmentId: "fantasy-06",
    segmentName: "Ancient Elven Bridge",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Elven Bridge Lantern (Guiding Flame)",
    objectName: "Elven Bridge Lantern",
    assetFile: "wizard-lantern.svg",
    defaultSegmentId: "fantasy-06",
    segmentName: "Ancient Elven Bridge",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Shrine Ancient Spellbook (Sacred Grimoire)",
    objectName: "Shrine Ancient Spellbook",
    assetFile: "ancient-spellbook.svg",
    defaultSegmentId: "fantasy-07",
    segmentName: "Celestial Shrine",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Shrine Wizard Lantern (Sanctuary Flame)",
    objectName: "Shrine Wizard Lantern",
    assetFile: "wizard-lantern.svg",
    defaultSegmentId: "fantasy-07",
    segmentName: "Celestial Shrine",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Terrace Floating Crystal (Arcane Conductor)",
    objectName: "Terrace Floating Crystal",
    assetFile: "floating-crystal.svg",
    defaultSegmentId: "fantasy-08",
    segmentName: "Mage Tower Terrace",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Terrace Spellbook (Conjuration Tome)",
    objectName: "Terrace Spellbook",
    assetFile: "ancient-spellbook.svg",
    defaultSegmentId: "fantasy-08",
    segmentName: "Mage Tower Terrace",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Fairy Ring Magic Mushroom (Circle Spores)",
    objectName: "Fairy Ring Magic Mushroom",
    assetFile: "magic-mushroom.svg",
    defaultSegmentId: "fantasy-09",
    segmentName: "Fairy Ring Glade",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Fairy Ring Rune Stone (Ancient Circle)",
    objectName: "Fairy Ring Rune Stone",
    assetFile: "rune-stone.svg",
    defaultSegmentId: "fantasy-09",
    segmentName: "Fairy Ring Glade",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Astral Wizard Lantern (Portal Flame)",
    objectName: "Astral Wizard Lantern",
    assetFile: "wizard-lantern.svg",
    defaultSegmentId: "fantasy-10",
    segmentName: "Astral Gateway",
  },
  {
    worldId: "fantasy-world",
    worldName: "Fantasy World",
    categoryLabel: "🔮 Fantasy: Astral Floating Crystal (Gateway Focus)",
    objectName: "Astral Floating Crystal",
    assetFile: "floating-crystal.svg",
    defaultSegmentId: "fantasy-10",
    segmentName: "Astral Gateway",
  },

  // ============================================
  // 10. Alien Planet (alien-04 to alien-10)
  // ============================================
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Chasm Survey Probe (Deep Scanner)",
    objectName: "Chasm Survey Probe",
    assetFile: "survey-probe.svg",
    defaultSegmentId: "alien-04",
    segmentName: "Spire Chasm",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Chasm Alien Creature (Crevasse Entity)",
    objectName: "Chasm Alien Creature",
    assetFile: "alien-creature.svg",
    defaultSegmentId: "alien-04",
    segmentName: "Spire Chasm",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Ridge Neon Crystal (Highland Mineral)",
    objectName: "Ridge Neon Crystal",
    assetFile: "neon-crystal.svg",
    defaultSegmentId: "alien-05",
    segmentName: "Xenolith Ridge",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Ridge Alien Flower (Exotic Flora)",
    objectName: "Ridge Alien Flower",
    assetFile: "alien-flower.svg",
    defaultSegmentId: "alien-05",
    segmentName: "Xenolith Ridge",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Marsh Alien Mushroom (Wetland Spore)",
    objectName: "Marsh Alien Mushroom",
    assetFile: "alien-mushroom.svg",
    defaultSegmentId: "alien-06",
    segmentName: "Bioluminescent Marsh",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Marsh Creature (Amphibious Alien)",
    objectName: "Marsh Creature",
    assetFile: "alien-creature.svg",
    defaultSegmentId: "alien-06",
    segmentName: "Bioluminescent Marsh",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Geyser Survey Probe (Thermal Telemetry)",
    objectName: "Geyser Survey Probe",
    assetFile: "survey-probe.svg",
    defaultSegmentId: "alien-07",
    segmentName: "Sulphur Geysers",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Geyser Neon Crystal (Mineral Vent)",
    objectName: "Geyser Neon Crystal",
    assetFile: "neon-crystal.svg",
    defaultSegmentId: "alien-07",
    segmentName: "Sulphur Geysers",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Outpost Surface Rover (Scout Vehicle)",
    objectName: "Outpost Surface Rover",
    assetFile: "surface-rover.svg",
    defaultSegmentId: "alien-08",
    segmentName: "Crater Outpost",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Outpost Alien Flower (Domesticated Botanical)",
    objectName: "Outpost Alien Flower",
    assetFile: "alien-flower.svg",
    defaultSegmentId: "alien-08",
    segmentName: "Crater Outpost",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Dunes Alien Creature (Sand Strider)",
    objectName: "Dunes Alien Creature",
    assetFile: "alien-creature.svg",
    defaultSegmentId: "alien-09",
    segmentName: "Amethyst Dunes",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Dunes Neon Crystal (Crystalline Formation)",
    objectName: "Dunes Neon Crystal",
    assetFile: "neon-crystal.svg",
    defaultSegmentId: "alien-09",
    segmentName: "Amethyst Dunes",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Horizon Survey Probe (Long Range Orbiter)",
    objectName: "Horizon Survey Probe",
    assetFile: "survey-probe.svg",
    defaultSegmentId: "alien-10",
    segmentName: "Prismatic Horizon",
  },
  {
    worldId: "alien-planet",
    worldName: "Alien Planet",
    categoryLabel: "🪐 Alien: Horizon Alien Mushroom (Giant Spore Stalk)",
    objectName: "Horizon Alien Mushroom",
    assetFile: "alien-mushroom.svg",
    defaultSegmentId: "alien-10",
    segmentName: "Prismatic Horizon",
  },
];
